---
# All plays in this playbook target the build host, but most be invoked separately,
# since we're using wrapper roles for the build. If you add multiple child roles with
# the same parent in the same play, Ansible conflates the dependencies, and only the
# last wrapper role will run. This is a known bug and will be fixed in v2.0.
- name: Build SecureDrop application Debian package from local repository.
  hosts: build
  vars_files:
    # The App Server vars are only necessary for building the securedrop-app-code package,
    # for the `development_dependencies` apt packages. Without these packages, the deb file
    # will build successfully, but fail on installation. See the comments in the regression
    # spectests on the build host for details.
    - group_vars/securedrop_application_server.yml
  roles:
    - { role: build-securedrop-app-code, tags: [build, rebuild, securedrop-app-code] }
  sudo: yes

- name: Build SecureDrop OSSEC Server Debian package from local repository.
  hosts: build
  roles:
    - { role: build-securedrop-ossec-server, tags: [build, rebuild, ossec, securedrop-ossec-server] }
  sudo: yes

- name: Build SecureDrop OSSEC Agent Debian package from local repository.
  hosts: build
  roles:
    - { role: build-securedrop-ossec-agent, tags: [build, rebuild, ossec, securedrop-ossec-agent] }
  sudo: yes
