---
- name: Build securedrop-app-code deb package from local code.
  hosts: build
  vars_files:
    # The order of these files files is important, since each successive
    # include overrides vars in the previous files. Ordinarily we'd
    # use group memberships to manage the variable resolution order, but
    # since we're using Vagrant with Ansible, group management becomes tricky.
    - group_vars/securedrop.yml
    - group_vars/securedrop_application_server.yml
    - group_vars/development.yml
  roles:
    - role: build-securedrop-app-code
      tags: app-deb
  sudo: yes
  tags: rebuild

- name: Build OSSEC metapackages for server and agent.
  hosts: build
  vars_files:
  # The order of these files files is important, since each successive
  # include overrides vars in the previous files. Ordinarily we'd
  # use group memberships to manage the variable resolution order, but
  # since we're using Vagrant with Ansible, group management becomes tricky.
    - group_vars/securedrop.yml
    - group_vars/securedrop_application_server.yml
    - group_vars/development.yml
  # Providing custom vars at the playbook level to override the role defaults.
  vars:
    ossec_agent_files: ../securedrop-ossec-agent
    ossec_server_files: ../securedrop-ossec-server
  roles:
    - role: build-debian-package
      build_debian_package_name: securedrop-ossec-server
      build_debian_package_version: "{{ ossec_version }}+{{ securedrop_app_code_version }}"
      build_package_files_directory: "{{ ossec_server_files }}"
      build_debian_package_files_directories:
        - src: "{{ ossec_server_files }}"
          dest: ""
      tags:
        - ossec
        - securedrop-ossec-server

    - role: build-debian-package
      build_debian_package_name: securedrop-ossec-agent
      build_debian_package_version: "{{ ossec_version }}+{{ securedrop_app_code_version }}"
      build_debian_package_files_directories:
        - src: "{{ ossec_agent_files }}"
          dest: ""
      tags:
        - ossec
        - securedrop-ossec-agent

  sudo: yes
  tags: rebuild
