---
- name: Add FPF apt repository and install base packages.
  hosts: staging
  roles:
    - { role: common, tags: common }
    - { role: grsecurity, when: grsecurity, tags: [grsec, grsecurity] }
    - { role: install-local-packages, tags: install_local_packages,
        when: install_local_packages }
    - { role: tor-hidden-services, tags: tor }
  sudo: yes

- name: Configure OSSEC manager.
  hosts: mon-staging
  roles:
    - { role: ossec-server, tags: [ ossec, ossec_server ] }
  sudo: yes

- name: Configure SecureDrop Application Server.
  hosts: app-staging
  roles:
    - { role: ossec-agent, tags: [ ossec, ossec_agent ] }
    - { role: app, tags: app }
    - { role: app-test, tags: app-test }
  sudo: yes

  # Set iptables rules with exemptions for staging that permit direct access for SSH.
  # The overrides that permit direct access are managed in group_vars/staging.yml,
  # and default false in production environments, in order to force SSH traffic over Tor.
- name: Configure host firewalls (with direct access for staging).
  hosts: staging
  roles:
    - { role: restrict-direct-access, tags: [ common, restrict-direct-access ] }
  sudo: yes

- name: Perform backup of Application Server configuration.
  hosts: app-staging
  roles:
    - { role: backup, tags: backup }
  sudo: yes
