language: python
python:
  - '2.7'
virtualenv:
  system_site_packages: true
before_install:
  - redis-cli info
install:
  - pip install ansible
services:
  - redis-server
script:
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check install_files/ansible-base/securedrop-travis.yml
  - ansible-playbook -i inventory --connection=local --sudo --skip-tags=non-development install_files/ansible-base/securedrop-travis.yml
  # travis needs the config.py file ran owned by root in other environments it is the
  # securedrop_user default www-data
  - sudo chown root:root securedrop/config.py
  - sudo sh -c "export DISPLAY=:1; cd securedrop && ./manage.py test"
notifications:
  slack:
    secure: jmEgJkFg6IVLl78dbLPBUpWkVuHkQ+HtXHNoY4cdgx2Gq5kVDuLtBIuMK5ubbj3zsp99JIJZ9DFQlunCkoLYZ7PAKQ7fhfwLEWNFJiAajMTZF/nNKV2J4i0NyMBHeFQ5eagAe3wrGiY5sblTbnExY4zERcdGoC1S2UImWX0xMRw=
