site_name: SecureDrop
pages:
  - Home: index.md
  - Installing SecureDrop:
    - Installation Overview: install.md
    - Hardware Requirements: hardware.md
  - Contributing to SecureDrop:
    - Development Environment: develop.md
    - Running the Tests: spec_tests.md

theme: readthedocs
