---
site_name: SecureDrop
pages:
  - Home: index.md
  - Installation:
    - Getting started: installation/intro.md
    - Set up Tails USB Sticks: installation/setup_tails_usb_sticks.md
    - Set up Secure Viewing Station: installation/setup_svs.md
    - Set up Admin Workstation: installation/setup_admin_workstation.md
    - Install SecureDrop Application: installation/securedrop_app.md
    - Finalizing the Installation: installation/final_steps.md
    - Hardware Requirements: installation/hardware.md
    - Deployment Practices: installation/deployment_practices.md
    - Server Config: installation/ubuntu_config.md
    - Network Firewall: installation/network_firewall.md
    - OSSEC Alerts: installation/ossec_alerts.md
    - Yubikey Setup: installation/yubikey_setup.md

  - Support:
    - Source User Manual: source_user_manual.md
    - Journalist User Manual: journalist_user_manual.md
    - Admin User Manual: admin_interface.md
    - Using Tails: tails_guide.md
    - Google Authenticator: google_authenticator.md
    - Upgrading SecureDrop:
      - Upgrading from 0.2.1: 0.2.1-upgrade-to-0.3.x.md
      - Upgrading from 0.3-pre: 0.3-pre-upgrade-to-0.3.x.md
    - Printing with Tails: tails_printing_guide.md
    - Terminology: terminology.md
    - Threat Model: threat_model.md
    - Training Schedule: training_schedule.md

  - Contributing:
    - Development Environment: develop.md
    - Running the Tests:
      - Serverspec Tests: spec_tests.md
      - Automated CI Tests: snap_ci.md
    - AppArmor Profiles: apparmor_profiles.md
    - Building .deb packages: creating_deb.md

theme: yeti
