---
- name: install postfix
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: ossec_postfix_dependencies
  tags:
    - apt
    - postfix

- name: ensure postfix /etc/aliases is present and configured for ossec
  copy:
    src: aliases
    dest: /etc/aliases
  notify: update aliases
  tags:
    - postfix

  # By default /etc/ssl/certs should already exist.
  # However, Admins can override this directory path
  # when declaring a custom cert file, in which case
  # it would need to be created.
- name: ensure certificate directory exists
  file:
    path: "{{ smtp_relay_cert_dir }}"
    mode: "0755"
    owner: root
    group: root
  tags:
    - postfix
    - postfix_custom_cert

- name: configure sasl password for smtp relay
  template:
    src: sasl_passwd
    dest: /etc/postfix/sasl_passwd
    mode: 0400
  notify: update sasl_passwd db
  tags:
    - postfix
    - permissions

- name: ensure header_checks regex to strip smtp headers is present
  copy:
    src: header_checks
    dest: /etc/postfix/header_checks
  notify: postmap_header_checks
  tags:
    - postfix
    - hardening

- name: add custom cert (if provided)
  copy:
    src: "{{smtp_relay_cert_override_file}}"
    dest: "{{smtp_relay_cert_dir}}/{{smtp_relay_cert_override_file}}"
    mode: "0755"
    owner: root
    group: root
  when: smtp_relay_cert_override_file is defined and
        smtp_relay_cert_override_file != ''

  tags:
    - postfix
    - postfix_custom_cert

- name: configure postfix main.cf
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
  notify: restart postfix
  tags:
    - postfix

# TODO - name: configure postfix proxy
