version: 2
jobs:
  build:
    docker:
      - image: msheiny/pressfreedomci:latest
        environment:
          FPF_CI: true
          CI_SD_ENV: staging
          CI_AWS_TYPE: t2.small
          FPF_GRSEC: false
          TEST_REPORTS: /root/sd
    working_directory: /root/sd

    steps:
      - checkout

      - run:
          # Docs say it's shallow but scripts don't look like it
          name: Check whether we're shallow.
          command: git rev-list --count HEAD

      - run:
          # Shouldn't be necessary, because we're not shallow, but just checking.
          name: Prep repo.
          command: >
            git fetch origin develop &&
            git checkout develop &&
            git pull origin develop &&
            git checkout -

      - run:
          name: Determine whether CI should run (don't if docs-only)
          environment:
            TERM: xterm
          command: >
            git diff develop.."$CIRCLE_SHA1" --name-only

      - run:
          name: Installation pre-reqs
          command: pip install -U -r ./testinfra/requirements.txt

      - setup_remote_docker

      - run:
          name: Run molecule and manage tests
          command: make ci-go

      - run:
          name: Teardown environment
          command: make ci-teardown
          when: always

      - store_test_results:
          path: /root/sd/junit

      - store_artifacts:
          path: /root/sd/junit
