---
# Set relative path for the directory containing the app code.
# Making this a variable since it may be different in CI scripts,
# and be overridden there. The default is provided here.
securedrop_app_code_files: ../securedrop-app-code
securedrop_app_code_directory: ../../securedrop

build_debian_package_name: securedrop-app-code
build_debian_package_files_directories:
  - src: "{{ securedrop_app_code_files }}/"
    dest: ""
  - src: "{{ securedrop_app_code_directory }}"
    dest: var/www/

build_debian_package_extra_files:
  - src: "usr.sbin.apache2"
    dest: "etc/apparmor.d/"
  - src: "usr.sbin.tor"
    dest: "etc/apparmor.d/"

# Adds in libssl-dev and python-dev, both of which are crucial for a successful
# install with the built package. See comments in the build spectests for more info.
build_debian_package_extra_dependencies: "{{ development_dependencies }}"

build_debian_package_version: "{{ securedrop_app_code_version }}"
build_debian_package_pip_requirements: var/www/securedrop/requirements/securedrop-requirements.txt
build_debian_package_pip_wheel_directory: var/securedrop/wheelhouse

# TODO: Test YAML string handling here and make sure that linebreaks
# don't mess with the Debian control script (which supports one line for description).
build_debian_package_description: >
  Packages the SecureDrop application code pip dependencies
  and apparmor profiles. This package will put the apparmor
  profiles in enforce mode. This package does use pip to install the pip wheelhouse

# TODO: These vars are taken verbatim from the previous, hard-coded control file for
# securedrop-app-code. It has redundant entries. Once integration tests are stable, refactor.
build_debian_package_depends:
  - python-pip
  - apparmor-utils
  - gnupg2
  - haveged
  - python
  - python-pip
  - secure-delete
  - sqlite
  - apache2-mpm-worker
  - libapache2-mod-wsgi
  - libapache2-mod-xsendfile
  - redis-server
  - supervisor
