---
# gdebi is smart enough to pull down dependences listed in a .deb package
- name: install gdebi for dependency management in local packages
  apt:
    name: gdebi
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags:
    - install_local_pkgs

# This will look for packages in install_files/ansible-base
- name: if defined copy local deb packages to target system
  copy:
    src: ../../build/{{ item }}
    dest: /root/
  with_items: local_deb_packages
  tags:
    - install_local_pkgs

# There's a known bug in Ansible that causes installing
# .deb packages via the apt module to fail when invoked
# with `with_items`. See here:
# https://github.com/ansible/ansible-modules-core/issues/1178
# A temporary workaround is to use gdebi, which is smart
# enough to handle pulling down dependencies listed in the
# .deb package.
- name: if defined install local deb packages
  command: gdebi -n /root/{{ item }}
  with_items: local_deb_packages
  tags:
    - install_local_pkgs
