---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook

platforms:
  - name: ubuntu-14.04
    driver_plugin: vagrant
    driver_config:
      box: ubuntu/trusty64

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      hosts: default
