---
### Used by the common role ###
# ssh_users is defined in the site-specific.yml config
# monitor_ip is defined in the site-specific.yml config
# monitor_hostname is defined in the site-specific.yml config

# For setting the etc hosts entries
ip_info:
  - ip: "{{ monitor_ip }}"
    hostname: "{{ monitor_hostname }} securedrop-monitor-server-alias"

# Building the securedrop-app-code deb package
securedrop_pip_requirements: "{{ securedrop_code }}/requirements/securedrop-requirements.txt"
test_pip_requirements: "{{ securedrop_code }}/requirements/test-requirements.txt"
development_dependencies:
  - ipython
  - libssl-dev
  - ntp
  - python-dev
  - python-pip
  - ruby # to ensure `gem` command is available
  - tmux
  - vim

# Installing the securedrop-app-code.deb package
securedrop_app_code_deb: "securedrop-app-code-{{ securedrop_app_code_version }}-amd64" # do not enter .deb extension

### Used by the install_local_deb_pkgs role ###
local_deb_packages:
  - "securedrop-ossec-agent-2.8.2+{{ securedrop_app_code_version }}-amd64.deb"
  - "{{ securedrop_app_code_deb }}.deb"
  - "ossec-agent-2.8.2-amd64.deb"
  - "securedrop-keyring-0.1.0+{{ securedrop_app_code_version }}-amd64.deb"

# Configuring the tor hidden services
tor_instances:
  - service: ssh
    filename: app-ssh-aths
  - service: source
    filename: app-source-ths
  - service: journalist
    filename: app-journalist-aths

apparmor_profiles:
  - usr.sbin.tor
  - usr.sbin.apache2

agent_auth_rules:
  - "-A OUTPUT -d {{ monitor_ip  }} -p tcp --dport 1515 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT"
  - "-A INPUT -s {{ monitor_ip }} -p tcp --sport 1515 -m state --state ESTABLISHED,RELATED -j ACCEPT"
