---
build_debian_package_maintainer: SecureDrop Team <securedrop@freedom.press>
build_debian_package_homepage: https://securedrop.org

build_debian_package_description: >
  Packages the SecureDrop application code pip dependencies
  and apparmor profiles. This package will put the apparmor
  profiles in enforce mode. This package does use pip to install the pip wheelhouse

build_debian_package_local_directory: ../../build
